### ISSUE TITLE
Unable to execute checkout.sh normally

### ISSUE THREAD

**Issue by wills06** [shorebirdtech/build_engine#24]
When I execute ./checkout.sh ./build/ the following error appears:

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git@github.com:shorebirdtech/dart-sdk.git /Users/***/WorkSpace/flutter/build_engine/build/engine/src/third_party/_gclient_dart_2b29tlv4' in '/Users/***/WorkSpace/flutter/build_engine/build/engine'

[0:01:55] Cloning into '/Users/***/WorkSpace/flutter/build_engine/build/engine/src/third_party/_gclient_dart_2b29tlv4'...
[0:01:57] git@github.com: Permission denied (publickey).
[0:01:57] fatal: Could not read from remote repository.
[0:01:57] Please make sure you have the correct access rights
[0:01:57] and the repository exists.

Does it mean:
'dart_sdk_git': 'git@github.com:shorebirdtech/dart-sdk.git' 

Is this project closed source? Or is it just a fork of the official Dart-SDK?

**Comment by eseidel** [comment]
Our dart fork is closed for the time being. I'd like to make it open over time, but not yet sure how much of it.

You should be able to build for android by replacing our dart fork with the public dart 3.1 sources.

**Comment by eseidel** [comment]
As far as I'm aware, you're only the second person ever to attempt to build our engine fork.  I'm happy to help make that possible (at least the public android side) but so far there has been very little demand.  Right now we're focused on making our iOS product production ready and then I'm interested in reevaluating what parts of our Dart fork are/aren't open some months down the line.

**Comment by wills06** [comment]
okay, thank you @eseidel
